---
Name: toastnz-webp
---

SilverStripe\Core\Injector\Injector:
  Intervention\Image\ImageManager:
    constructor:
      - { driver: WebP }  

SilverStripe\Assets\Storage\DBFile:
  extensions:
    - Intervention\Image\WebP\Extensions\DBFileExtension

SilverStripe\Assets\File:
  allowed_extensions:
    - webp

